// Code generated by MockGen. DO NOT EDIT.
// Source: bookmark.go
//
// Generated by this command:
//
//	mockgen -source=bookmark.go -destination=mock/mock_bookmark.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nnno/my-raindrop-io-mcp-server/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBookmarkRepository is a mock of BookmarkRepository interface.
type MockBookmarkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookmarkRepositoryMockRecorder
	isgomock struct{}
}

// MockBookmarkRepositoryMockRecorder is the mock recorder for MockBookmarkRepository.
type MockBookmarkRepositoryMockRecorder struct {
	mock *MockBookmarkRepository
}

// NewMockBookmarkRepository creates a new mock instance.
func NewMockBookmarkRepository(ctrl *gomock.Controller) *MockBookmarkRepository {
	mock := &MockBookmarkRepository{ctrl: ctrl}
	mock.recorder = &MockBookmarkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookmarkRepository) EXPECT() *MockBookmarkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookmarkRepository) Create(ctx context.Context, params entity.CreateParams) (*entity.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookmarkRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookmarkRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockBookmarkRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookmarkRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookmarkRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockBookmarkRepository) Get(ctx context.Context, id int) (*entity.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBookmarkRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBookmarkRepository)(nil).Get), ctx, id)
}

// Search mocks base method.
func (m *MockBookmarkRepository) Search(ctx context.Context, params entity.SearchParams) ([]entity.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params)
	ret0, _ := ret[0].([]entity.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockBookmarkRepositoryMockRecorder) Search(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockBookmarkRepository)(nil).Search), ctx, params)
}

// Update mocks base method.
func (m *MockBookmarkRepository) Update(ctx context.Context, id int, params entity.UpdateParams) (*entity.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(*entity.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBookmarkRepositoryMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookmarkRepository)(nil).Update), ctx, id, params)
}
